# Generated by Django 5.1.2 on 2024-10-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('explanation', models.TextField()),
                ('score', models.IntegerField()),
                ('tag_type', models.CharField(choices=[('Numeros', 'Números'), ('Geometria', 'Geometría'), ('Algebra y Funciones', 'Álgebra y Funciones'), ('Probabilidad y Estadística', 'Probabilidad y Estadísticas')], max_length=250)),
                ('alternatives', models.ManyToManyField(to='core.alternativeschema')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('questions', models.ManyToManyField(to='core.questionschema')),
            ],
        ),
    ]
